### ISSUE TITLE
Add internationalization and localization support with gettext and Weblate

### ISSUE THREAD

**Issue by raphaelh** [elboulangero/goodvibes#14]
* gettext(http://www.gnu.org/software/gettext/) is the way to go for this, and there's a starting guide here: https://docs.weblate.org/en/latest/devel/starting.html

* [Weblate ](https://weblate.org/)is a nice FOSS web-translation tool which can either be self-hosted, or can host FOSS projects for free

It comes with native support for GitHub and Gitlab hooks: https://docs.weblate.org/en/latest/admin/continuous.html

**Comment by elboulangero** [comment]
Hey Raph, thx for the links.

I don't know yet how translations will be managed, I'll wait a bit for translators to show up. Thx for the `Weblate` link, I didn't know that.

Other possibilities I know of:

- https://www.transifex.com/
- http://translationproject.org/

Happy new year btw ^_^

**Comment by elboulangero** [comment]
The package is already `gettext` ready, here's a quick way to start a French translation:

    cd po
    msginit -i goodvibes.pot -l fr --no-translator -o fr.po

To add the French language to the build system:

    echo fr >> po/LINGUAS

Po files can then be updated any time with:

    make -C po/ update-po

**Comment by raphaelh** [comment]
There are several other possibilities: Transifex, Pootle, Zanata, TranslationWiki

but from what I've heard, Weblate is the best one, and what's more, it's free software :)

If you add the Goodvibes to Weblate (with free hosting as it's free software), it will be easier for people to contribute translations without needing to download the source, run some obscure commands depending on what you want to achieve, and make a pull request to get your changes accepted. It also makes it easier for people to collaborate on the translation.

Happy new year :)

**Comment by elboulangero** [comment]
Goodvibes is now on Weblate, let's translate !

https://hosted.weblate.org/projects/goodvibes/
