### ISSUE TITLE
Add the project to Travis CI

### ISSUE THREAD

**Issue by raphaelh** [elboulangero/goodvibes#15]
https://travis-ci.org/ and http://travis.debian.net/

And also:
* https://codecov.io/
* https://www.codacy.com/
* https://readthedocs.org/
* https://bestpractices.coreinfrastructure.org/

**Comment by elboulangero** [comment]
Gosh that's a lot to read ! I know almost none of that, so it's welcome.

Anyway. For continuous integration, I just set it up last week in 2276ef4. I chose to go with Shippable and custom docker images hosted on Docker Hub. The repository containing Dockerfiles is available at https://github.com/elboulangero/goodvibes-docker.

I currently have images for Ubuntu, Debian and Fedora. I'm waiting to see more official images appear on DockerHub to add more distributions.

**Comment by elboulangero** [comment]
BTW, I wrote an article explaining the workflow with docker and shippable, for people interested. It's available on my blog: http://hacking.elboulangero.com/2017/01/13/docker-shippable.html

But a picture speaks more than word, so...

           ----------------------
          | dockerfiles @ github |
           ----------------------
                          \
                     source for
                            \
                      ---------------------
                     | images @ docker hub |
                      ---------------------
                            /
                       pull from
                          /
                 -------------------
                | build @ shippable |
                 -------------------
                      /
                  trigger
                    /
         ------------------
        | project @ github |
         ------------------
