### ISSUE TITLE
Implement MPRIS2 Playlists interface

### ISSUE THREAD

**Issue by elboulangero** [elboulangero/goodvibes#16]
At the moment, Goodvibes only implements the mpris2 *Tracklist* interface.

The reason is that, strictly speaking, Goovibes has only one list of radio stations, that's to say, one tracklist. Goodvibes has no playlist to speak of.

The problem is that Ubuntu and Gnome mpris applets don't use the *Tracklist* interface, they only use the *Playlists* interface. It makes sense for most music player, where **each track is a song**, and a playlist is a collection of songs. You just want to pickup a playlist, you don't really need to select a particular track in it.

But Goodvibes is a bit different, since **each track is a stream**. So you want to be able to see your tracklist, and choose which track (aka radio station) to listen to. Without that feature, the existing mpris applets fall short for Goodvibes.

Ok, so for now on I will implement the *Playlists* interface, without touching the existing *Tracklist* interface. Which means that each radio station will be a Track AND a playlist at the same time. Yep, I'm abusing the mpris2 spec here, I confess. Time will tell how good/bad it is.

**Comment by raphaelh** [comment]
This is how they're planning to do in Gradio: https://github.com/haecker-felix/gradio/issues/91
