### ISSUE TITLE
Expose customization for GStreamer output

### ISSUE THREAD

**Issue by elboulangero** [elboulangero/goodvibes#21]
Some users who have multiple soundcards might want to choose which soundcard should be used for the output. Apparently this is easy for PulseAudio users (PulseAudio manages that), but for ALSA users, there's no solution.

The easy way would be to do a bit like Quodlibet, and let user specify the output pipeline.

![screenshot_2017-01-18_09-16-52](https://cloud.githubusercontent.com/assets/1942580/22091074/77175c18-de27-11e6-9238-9d91a5326e0b.png)

The upside is that it offers quite a lot of possibilities, not only choosing the soundcard. The downside is that it's only for advanced users (not everybody knows what to write here).

So, I think I'll implement it like Quodlibet, with a little addition: a checkbox in front of the text entry, to allow _disabling_ it without _erasing_ the line. So that users can easily disable it (for example when they go on a trip and don't have their USB soundcard anymore) and re-enable it afterward, without struggling to remember the magic line they used.

Along with that, I should put a nice, long tooltip which provides common examples, especially for choosing the ALSA soundcard (which I believe is the usage number one for this setting).

Adding use cases in the wiki as well wouldn't hurt.

**Comment by raphaelh** [comment]
To keep the UI simple for users who don't need to customize things, maybe you could add a button or checkbox to enable advanced settings?

**Comment by elboulangero** [comment]
Hmm, I'm not a big fan of this "Advanced setting" thing to be honest, as long as the UI is not cluttered by too much stuff I prefer to keep everything on the same level. I think QuodLibet are quite good on that, they find a right balance between enough settings but not too much. If you look at the settings of Audacious in comparison, it's a bit more furnished, but way more messy...

**Comment by sebas22** [comment]
Thanks a lot for for attending my request !
I think the way you see this feature will perfectly do the job.
Maybe a link pointing to your wiki under the text box will quickly lead the user to the most common exemples, and maybe let them add some if necessary ?
