### ISSUE TITLE
Allow changing user-agent per radio

### ISSUE THREAD

**Issue by elboulangero** [elboulangero/goodvibes#23]
Some radios request a specific user-agent (that's what I was told, I still need an example). I don't know how easy it is to configure the user-agent from GStreamer, but if it's easy, we could expose that in the station settings, a "custom user-agent".

**Comment by raphaelh** [comment]
I've never seen this either, but at least if you set a default user-agent to "goodvibes", this will let the radio administrators about goodvibes if they look at their logs :smile:

**Comment by elboulangero** [comment]
Yep, I know, this is part of this issue even if I didn't mention it :)

**Comment by raphaelh** [comment]
In http://git.suckless.org/surf/commit/?id=5501d75d2c97398d3ffddb200061cb93cc90bac3 it seems to be set like this:
`g_object_set(G_OBJECT(settings), "user-agent", ua, NULL);`



Issue in radiotray: https://bitbucket.org/carlmig/radio-tray/issues/27/user-agent

Some reading about user agent checking: http://www.radiosure.com/forum/viewtopic.php?f=4&t=2188

**Comment by elboulangero** [comment]
Implemented but not integrated in the UI.

**Comment by elboulangero** [comment]
I dropped a line in the wiki about this secret feature. I'm very doubtful that anybody will use that.
