### ISSUE TITLE
Only goodvibes.desktop will show in  sound menu in Ubuntu

### ISSUE THREAD

**Issue by mc4man** [elboulangero/goodvibes#26]
com.elboulangero.Goodvibes.desktop does not produce any sound menu entry
com.elboulangero.goodvibes.desktop  does not produce any sound menu entry
Goodvibes.desktop does not produce any sound menu entry
goodvibes.desktop works fine as expected

i.e. - 
sudo cp  /usr/share/applications/com.elboulangero.Goodvibes.desktop  /usr/share/applications/goodvibes.desktop
sudo rm  /usr/share/applications/com.elboulangero.Goodvibes.desktop

Why the convoluted & relatively non-standard .desktop name?

**Comment by elboulangero** [comment]
Hi mc4man,

> Why the convoluted & relatively non-standard .desktop name?

This is how the desktop file should be named, according to the latest version (1.1 at the moment) of the spec available at: https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-1.1.html

Let me quote them: 
> The application must name its desktop file in accordance with the naming recommendations in the introduction section (e.g. the filename must be like org.example.FooViewer.desktop).

Note that the part about D-Bus activable services is an addition in the 1.1 spec from 2016-12-24. The previous version from 2014 doesn't mention anything like that, as far as I know.

If I have a quick look on Ubuntu LTS 16.04, I see that the core apps from gnome already respect that, but that's all.

```
ls -1 /usr/share/applications/ | grep -e 'org\.' -e 'com\.' -e 'net\.'
com.elboulangero.Goodvibes.desktop
org.gnome.baobab.desktop
org.gnome.Calendar.desktop
org.gnome.Cheese.desktop
org.gnome.DiskUtility.desktop
org.gnome.FileRoller.desktop
org.gnome.font-viewer.desktop
org.gnome.gedit.desktop
org.gnome.Nautilus.desktop
org.gnome.Screenshot.desktop
org.gnome.Software.desktop
org.gnome.Totem.desktop
```

**Comment by elboulangero** [comment]
How do you get to see the sound menu in Ubuntu ? I click on "Search your computer", then on "Application". This gives me a list of applications, and Goodvibes is part of it, so it looks OK to me. But that's as far as my Ubuntu skills go :)

**Comment by mc4man** [comment]
The sound menu is in the top right set of indicators. 
If one was to manually add com.elboulangero.Goodvibes.desktop to 'interested players' in dconf
(- com.canonical.indicator.sound interested-media-players) then goodvibes player would appear in the sound menu but not be of much use, i.e., no controls, playlist, ect
For whatever reason only goodvibes.desktop both adds & gives one a proper mpris entry, screen attached.

![menu](https://cloud.githubusercontent.com/assets/5961561/22171983/b8e4ea78-df69-11e6-9892-964bc8d66a4b.png)

Maybe it's some flaw in ubuntu as I have noticed recently the use of those extended .desktop names for whatever reason. The name as used in the dbus service file is fine, it just seems to be about the the name of the .desktop file...

**Comment by khurshid-alam** [comment]
I agree. However I wonder how gnome apps work?

**Comment by elboulangero** [comment]
Ok, my bad, I forgot to change the desktop filename as provided by the mpris2 backend. This is now fixed. Good catch, thanks for reporting !

For everyone facing this issue, I recommend the following workaround (as root, add `sudo`):
```
cd /usr/share/applications && \
ln -s com.elboulangero.Goodvibes.desktop goodvibes.desktop
```

This will be fixed in the next release, coming pretty soon I guess.
