### ISSUE TITLE
Add a "toggle play" command to goodvibes-client

### ISSUE THREAD

**Issue by oliverpool** [elboulangero/goodvibes#37]
I would like to have a `goodvibes-client pause` (or `goodvibes-client toggle`) command to play or pause (depending on the `goodvibes-client playing` state).

This would simplify the logic that I had to implement for my keybinding :-)

**Comment by elboulangero** [comment]
Makes sense, I will add that, I'm working on this part at the moment. Expect to see that very quickly :)
