### ISSUE TITLE
Add options to the `goodvibes-client current` command

### ISSUE THREAD

**Issue by oliverpool** [elboulangero/goodvibes#38]
Currently, the `goodvibes-client current` displays the name of the station with the url of the stream (with some fancy colors).

It would be great to have a way to get only the name or the URL of the station (without formatting).

Maybe something along:
```
goodvibes-client current name
goodvibes-client current uri
goodvibes-client current ... # artist, title, album, genre, year, comment
```

**Comment by elboulangero** [comment]
Well at the moment the "current" command also displays the artist, tittle and so on, according it's provided by the stream. But the output is not meant to be parsed, it's just supposed to be read as it by the user. That's why I use a bit of bold and stuff like that, to try to make it nice for people reading it.

What you want is something that can be parsed, if I understand properly ?

**Comment by oliverpool** [comment]
Exactly.

All the issues that I opened are to integrate goodvibes into my [i3](http://i3wm.org/) setup:
* bind my own keys (with a toggle play/pause)
* display the currently playing station in the status bar (via a custom script)

I got this to work by parsing the output via `sed`, but it's quick dirty (to say the least ;-)

**Comment by elboulangero** [comment]
I recommend to use directly the dbus interface then, it's more reliable, and the output shouldn't change anytime soon. Goodvibes exposes two interfaces on DBus: its own native interface and the mpris2 interface.

Example using the native dbus interface:

    qdbus com.elboulangero.Goodvibes \
          /com/elboulangero/Goodvibes \
          com.elboulangero.Goodvibes.Player.Current

Or using the mpris2 interface:

    qdbus org.mpris.MediaPlayer2.Goodvibes \
          /org/mpris/MediaPlayer2 \
          org.mpris.MediaPlayer2.Player.Metadata



I suggest you have a look at the [MPRIS2 Specification](https://specifications.freedesktop.org/mpris-spec/latest/). MPRIS2 should be the preferred interface for two reasons:
- it won't change, therefore won't break your script (while the native interface, I might change it anytime if need be).
- you can re-use your work with any other media player that implements the mpris2 interface.

The drawback is that the mpris2 interface as its limitations. I'd say, as a rule of thumb, use mpris2 whenever possible.

FYI, there are different dbus command-line clients: `qdbus` (qt client), `dbus-send` (official dbus client) and `busctl`(systemd client).

**Comment by oliverpool** [comment]
Ok, thank you for all this informations!

I think it could be really valuable to add this to the wiki :-)

**Comment by elboulangero** [comment]
Wiki updated:

https://github.com/elboulangero/goodvibes/wiki/Tips-And-Tricks
