### ISSUE TITLE
Add native tray icon support for desktop environments

### ISSUE THREAD

**Issue by elboulangero** [elboulangero/goodvibes#4]
At the moment, we use GtkStatusIcon (deprecated) to display the tray icon.

I chose it because I personally use Openbox/Tint2, and with these guys there's no other way to display the tray icon.

Ok, but it would be nice to implement different back-ends for the tray icon, so that it's native on other desktop environments.

- Ubuntu, KDE: libappindicator
- Gnome: some gnome stuff I guess
- Something else ?

The idea would be to have these different back-ends optional at compile-time, and compiled as shared libraries I guess. So that when packaged and installed, back-ends are installed only according to what's already installed, or something like that.

There's also a need for run-time detection, in case KDE and Gnome are both installed for example, then we must be able to know which one is running, then launch the right tray back-end.

That would be quite an interesting thing to implement, I wish I do that at some point.

**Comment by elboulangero** [comment]
Ok, here comes the result of my personal investigations on the matter.

- DE: Desktop Environment
- TI: Tray Icon

| DE | Current TI | Legacy TI | MPRIS Applet |
| ---- | --------- | ---------- | --------------- |
| Gnome | none | GtkStatusIcon | yes |
| Elementary | none | none | yes |
| Unity | AppIndicator | none | yes |
| KDE | AppIndicator | none | yes |
| Cinnamon | GtkStatusIcon | none | yes |
| Mate | GtkStatusIcon | none | no |
| XFCE | GtkStatusIcon | none | no |
| LXDE | GtkStatusIcon | none | no |

Some comments on these different desktop environments:
- From Gnome 3.16, GtkStatusIcons are displayed in the [bottom-left corner of the screen][1]. Clearly, these icons are on the way out, and my guess is that it will be completely removed in the future.
- Apparently Elementary used AppIndicator for a while, but it's [gone since version 0.4][2].
- Unity and KDE agreed on AppIndicator, so I guess they will support it for a while. GtkStatusIcon is not supported there. KDE [dropped support for xembed][3] with Plasma 5 (xembed is the protocol GtkStatusIcon relied on, if I understand properly).
- Cinnamon and Mate still support GtkStatusIcon for sure, I don't know about AppIndicator.
- Old-school DE like XFCE or LXDE didn't make their move yet, they still stick with GtkStatusIcon.

More comments:
- GtkStatusIcon is deprecated long ago, so using it is not a good idea.
- Switching to libappindicator seems like a good move, especially because it [falls back to GtkStatusIcon][5] on systems that don't support the AppIndicator API. However:
  - it will never work on Gnome based systems
  - it's much more restricted than GtkStatusIcon (only allows to display a simple menu, only one click)

What's the best solution then ?

It seems to me that DE want to get rid of the notification area nowadays (Gnome like), or at least to control it more tightly than before (Unity like). That's a problem to me since my initial goal was to have an application which GUI was only shown when clicking on the tray icon. I can only do that with GtkStatusIcon, which is dying.

Now, what's interesting is to see that all the modern DE now provide an MPRIS applet with basic functionalities: play, stop, prev, next + notifications when trakcs change. And this is enough for a daily usage with goodvibes.
 
So my current point of view now is just to STOP completely bothering myself with tray icon. I think I'll just get back to a normal, plain window interface. This will be used to have plain control on goodvibes, that is, to configure the radio list. When it's done, and the only thing left to do is just to listen to the radios, why not launching goodvibes without the UI, and let the mpris applet do the job of controlling the player ?

[1]: http://superuser.com/q/941940/521602
[2]: http://elementaryos.stackexchange.com/a/4227
[3]: http://blog.martin-graesslin.com/blog/2014/03/system-tray-in-plasma-next/
[5]: https://wiki.ubuntu.com/DesktopExperienceTeam/ApplicationIndicators#Custom_Fallbacks

**Comment by elboulangero** [comment]
Oh yes you're right, I missed that

**Comment by raphaelh** [comment]
Here is Gradio with support for album cover, artist and track name:
![](https://cloud.githubusercontent.com/assets/542500/21719566/bbb18af0-d41e-11e6-817b-3728cefe69b8.png)

**Comment by elboulangero** [comment]
There's no cover support in Goodvibes, but metadata should show up if it's embedded in the stream. Didn't test though...
