### ISSUE TITLE
Station URI missing after restart

### ISSUE THREAD

**Issue by ZEROF** [elboulangero/goodvibes#41]
Hi,

Every time when I start goodvibes station URI is missing.

![goodvibes](https://cloud.githubusercontent.com/assets/2687905/22731745/fdc101c8-edeb-11e6-97a4-0a290cde90da.png)

**Comment by elboulangero** [comment]
Which version of Goodvibes are you running ?

You can find that in the *About* window, or you can open a terminal and run

    goodvibes -v

I tried to add this station, with url `http://streaming.orion.rs.:8030/listen.pls` (please confirm that it's also the url you use), and it works. Then I quit and restart Goodvibes, and the url is still there.

**Comment by ZEROF** [comment]
HI,

Goodvibes 0.1
Copyright (C) 2015-2017 Arnaud Rebillout <elboulangero@gmail.com>
Compiled against: GLib 2.48.1, GStreamer 1.8.2.0, GTK+ 3.18.9
Running along   : GLib 2.48.2, GStreamer 1.8.2.0, GTK+ 3.18.9

**Comment by elboulangero** [comment]
Hi,

there was major changes between the 0.1 and 0.2 versions, that impact the way stations are saved. I think you should just update to the latest version and the problem will be fixed. If you install from the [Launchpad PPA](https://launchpad.net/~elboulangero/+archive/ubuntu/goodvibes), you just need to upgrade your system.

**Comment by ZEROF** [comment]
Right man, updated to 0.2.1, all ok now.

Thanks for your time.
