### ISSUE TITLE
goodvibes --status-icon crash at startup

### ISSUE THREAD

**Issue by milouse** [elboulangero/goodvibes#44]
While trying to package the new 0.3 release, I got an error after building / installing the new version. Launching goodvibes alone is ok, but launching `goodvibes --status-icon` crash with the following error message:

    ERROR:ui/gv-ui-helpers.c:39:gv_builder_load: 'file_found' should not be NULL

Here are the content of my /usr/share/goodvibes folder:

    $ ll /usr/share/goodvibes/ui/
    total 52K
    -rw-r--r-- 1 root root 1,3K 22 févr. 14:34 app-menu.glade
    -rw-r--r-- 1 root root 9,4K 22 févr. 14:34 main-window.glade
    -rw-r--r-- 1 root root 1,6K 22 févr. 14:34 menubar.glade
    -rw-r--r-- 1 root root  28K 22 févr. 14:34 prefs-window.glade
    -rw-r--r-- 1 root root 1,8K 22 févr. 14:34 station-dialog.glade

**Comment by elboulangero** [comment]
My bad, there's one file missing, I forgot to add it in the Makefile. Let me fix that and tag a 0.3.1.

**Comment by milouse** [comment]
yep, just found out `status-icon-menu.glade` is missing in the Makefile: https://github.com/elboulangero/goodvibes/blob/517ba5ccc21a4b958fc7faec500b5ba3f5aec252/data/Makefile.am#L105

**Comment by elboulangero** [comment]
Alright, it's all fixed and pushed on the `master`branch !
