### ISSUE TITLE
goodvibes --status-icon does not work for desktop file

### ISSUE THREAD

**Issue by dln949** [elboulangero/goodvibes#45]
I am running Ubuntu 16.10, Unity desktop.  

I have Goodvibes 0.3.1 installed.  

If, from the terminal, I run   goodvibes --status-icon   everything works as expected.  

However, if I create a desktop file that has as the command   goodvibes --status-icon    then Goodvibes starts, but it starts with the UI displayed, instead of "minimized" to the system tray area.  

(On my system other applications are able to be successfully "minimized" to the system tray".  Only Goodvibes seems to have this problem.)

**Comment by elboulangero** [comment]
Can you paste me your desktop file so that I try to reproduce ? Can you also give me a desktop file that you use successfully for another application ?

**Comment by dln949** [comment]
On 02/24/2017 08:23 PM, Arnaud Rebillout wrote:

Can you paste me your desktop file so that I try to reproduce ? Can you also give me a desktop file that you use successfully for another application ?

**Comment by elboulangero** [comment]
Close that with release `0.4` if there's no feedback
