### ISSUE TITLE
Set referer

### ISSUE THREAD

**Issue by nick75e** [elboulangero/goodvibes#46]
Hi,

Like you allowed to set a user-agent, can you do the same for the referer?
Thank you.

_P.S.: your software is awesome, great replacement for RadioTray_

**Comment by elboulangero** [comment]
I will look into that when I have time :)

Setting the `user-agent` was trivial, since [libsoup supports that][1]. There's no such thing for the referer.

BTW, what's the use-case for that ?

Cheers.

[1]: https://developer.gnome.org/libsoup/stable/SoupSession.html#SoupSession--user-agent

**Comment by nick75e** [comment]
French radio station [NRJ](http://www.nrj.fr/) has recently restricted access to its streams. If you block or fake your user-agent, the web page will remain silent when you click play.

Hope you can do something.

**Comment by elboulangero** [comment]
Hey, is it still a feature that is needed ? I just had a look on [radio browser](http://www.radio-browser.info/gui/#/edit/21353), the URL for NRJ is provided there, I tried it in Goodvibes, it works great.

If there's no need then I will close this issue.

**Comment by nick75e** [comment]
You're right, the link works and some of the webradios work again, they apparently went back on their decision. So I guess there's no need for you to implement the referer anymore.
Thanks for the update anyway!
