### ISSUE TITLE
Ubuntu 17.10

### ISSUE THREAD

**Issue by khatchad** [elboulangero/goodvibes#63]
The package install via apt doesn't work on Ubuntu 17.10. The repo isn't found.

**Comment by elboulangero** [comment]
Hi !

What's the content of your ppa file ? It should be a file somewhere in `/etc/apt/sources.list.d/` or something like that, I'm not sure as I don't have any Ubuntu around.

The file should have this content:

    deb http://ppa.launchpad.net/elboulangero/goodvibes/ubuntu xenial main
    deb-src http://ppa.launchpad.net/elboulangero/goodvibes/ubuntu xenial main

I published only a package for `xenial` on Launchpad, so you should make sure that the distribution that is mentioned in your ppa file is `xenial` and not `zesty`.

Waiting for your feedback...

**Comment by khatchad** [comment]
I'm unsure if I can answer all of your questions, but I am basically following the directions mentioned at https://github.com/elboulangero/goodvibes#ubuntu. I follow the link to https://launchpad.net/~elboulangero/+archive/ubuntu/goodvibes. 

Then, I execute `sudo add-apt-repository ppa:elboulangero/goodvibes`:
```
$ sudo add-apt-repository ppa:elboulangero/goodvibes
[sudo] password for rk1424: 
 Goodvibes is a lightweight internet radio player for GNU/Linux. It offers a simple way to have your favorite radio stations at easy reach.
 More info: https://launchpad.net/~elboulangero/+archive/ubuntu/goodvibes
Press [ENTER] to continue or Ctrl-c to cancel adding it.

gpg: keybox '/tmp/tmpecly2jnd/pubring.gpg' created
gpg: /tmp/tmpecly2jnd/trustdb.gpg: trustdb created
gpg: key 93A56C5D2CB50F8B: public key "Launchpad PPA for elboulangero" imported
gpg: Total number processed: 1
gpg:               imported: 1
OK
```
Next, I execute `sudo apt-get update`, and get the following error:
```
...
Err:32 http://ppa.launchpad.net/elboulangero/goodvibes/ubuntu artful Release
  404  Not Found
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/elboulangero/goodvibes/ubuntu artful Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by khatchad** [comment]
```
$ uname -a
Linux rk1424-XPS-13-9350 4.13.0-16-generic #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by elboulangero** [comment]
The problem here is that `apt` expects to find a repository for Ubuntu Artful, as you can see on this line:

    E: The repository 'http://ppa.launchpad.net/elboulangero/goodvibes/ubuntu artful Release' does not have a Release file.

And up to now I packaged Goodvibes only for Ubuntu Xenial.

Ok, so this is fixed by now, I just copied the package from `xenial` to `artful`, as explained [here](https://askubuntu.com/q/30145/424636). This will fix the apt error, so you can `apt-get update` again right now.

After that, there's a little risk of failure when you will launch Goodvibes, and if such thing happens, please let me now, I will have to re-build the package instead of just copying it like I did.

**Comment by khatchad** [comment]
Looks good. Thanks!
