### ISSUE TITLE
No indicator on Ubuntu 17.10

### ISSUE THREAD

**Issue by khatchad** [elboulangero/goodvibes#64]
I don't see an indicator like you have on the wiki pages under Ubuntu 17.10.

**Comment by khatchad** [comment]
Ah, actually, I see it when I press the date.

**Comment by elboulangero** [comment]
Well I guess it depends on your Ubuntu version, it should be displayed somewhere.

Indeed in GNOME, the multimedia player controls appear when you click on the date, and the latest Ubuntu is based on GNOME, so it might be the same in Ubuntu now.

For some technical details, any multimedia player that implements the [MPRIS2](https://specifications.freedesktop.org/mpris-spec/latest/) interface will show up there when you click on the date, it's basically a generic remote control, nothing specific to Goodvibes.

Cheers
