### ISSUE TITLE
Erreur de compilation sur Ubuntu 16.04

### ISSUE THREAD

**Issue by trentanel** [elboulangero/goodvibes#65]
Bonjour,
Quand je veux compiler Goodvibes sur une nouvelle installation à jour d'Ubuntu 16.04, je rencontre cette erreur.`
./configure: line 4211: syntax error near unexpected token `$as_echo'`

**Comment by elboulangero** [comment]
Bonjour,

il faudrait regarder ce qui se trouve dans le fichier `./configure` à la ligne 4211, et me copier-coller cette ligne. C'est probablement une dépendance qui n'est pas installée sur votre système et que j'ai du oublier de documenter.

Comme le fichier `./configure` est un fichier généré, je ne peux pas regarder par moi même, le fichier généré sur mon système est surement différent à la ligne 4211 par rapport au votre.

En cas, copier-coller moi le bloc de lignes autour de la ligne 4211, en m'indiquant exactement quelle est la ligne 4211, et je devrais pouvoir m'en sortir avec ca.

Merci !

**Comment by trentanel** [comment]
```
checking for ranlib... ranlib
checking for ar... ar
checking the archiver (ar) interface... ar
./configure: line 4211: syntax error near unexpected token `$as_echo'
./configure: line 4211: `$as_echo "---- I18n ----"'
```
Extrait du fichier configure. La ligne 4211 est celle qui contient :  $as_echo "---- I18n ----"
[configure.txt](https://github.com/elboulangero/goodvibes/files/1505069/configure.txt)
Je l'ai renommé en configure.txt pour faire plaisir au système d'upload et le joindre à ma réponse.

```

# ------------------------------------- #
#      Internationalization (i18n)      #
# ------------------------------------- #

$as_echo "---- I18n ----"

# Init gettext
{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for a sed that does not truncate output" >&5
$as_echo_n "checking for a sed that does not truncate output... " >&6; }
if ${ac_cv_path_SED+:} false; then :
  $as_echo_n "(cached) " >&6
else
            ac_script=s/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb/
     for ac_i in 1 2 3 4 5 6 7; do
       ac_script="$ac_script$as_nl$ac_script"
     done
```

**Comment by elboulangero** [comment]
Ok merci, si vous avez un moment, est-ce que vous pouvez tenter d'installer glib dev:

    apt-get install libglib2.0-dev

Puis retenter la commande `./configure` dans Goodvibes, ca devrait passer.

**Comment by trentanel** [comment]
Arf ! j'ai rendu la machine à son propriétaire et je n'ai pas d'autre Ubuntu sous la main pour le moment.
Désolé

**Comment by elboulangero** [comment]
Ok pas de souci, merci pour le feedback en tout cas !
