### ISSUE TITLE
Un *deb pour Goodvibes

### ISSUE THREAD

**Issue by trentanel** [elboulangero/goodvibes#66]
Bonjour,
Le wiki signale qu'un fichier .deb est disponible sur la page github.  Où se trouve-t-il svp ?

**Comment by elboulangero** [comment]
Bonjour,

j'ai corrigé le Wiki, il y a bien des paquets Debian disponibles, mais pas sur GitHub. Voir la page du projet pour les détails: https://github.com/elboulangero/goodvibes#installation-from-a-package-manager

**Comment by trentanel** [comment]
Merci, j'ai pu installer Goodvibes avec le PPA. C'est parfait.
