### ISSUE TITLE
Support for "NumberOfEvents" in pls playlist

### ISSUE THREAD

**Issue by orschiro** [elboulangero/goodvibes#67]
Dear @elboulangero,

Thanks for your work!

Just tried adding the following links:

```
MP3: http://www.abc.net.au/res/streaming/audio/mp3/local_adelaide.pls
AAC+: http://www.abc.net.au/res/streaming/audio/aac/local_adelaide.pls
```

But it doesn't seem to work. The stream it not playing. Always stops. 

Any ideas?

**Comment by elboulangero** [comment]
Hello !

I tried to add your playlist, and to play it in Goodvibes. I get the following error on the command-line:

    WARN 09:15:39 core/gv-playlist.c: parse_playlist_pls(): Failed to get 'NumberOfEntries': Key file does not have key 'NumberOfEntries' in group 'playlist'
    WARN 09:15:39 core/gv-playlist.c: on_message_completed(): Faild to parse playlist

I will fix that in the next version.

In the meantime, what you can do is parse the playlist by yourself ! It's easy, the playlist is a simple text file, so you can download it and look at the content with a text editor.

If your a command-line guy, you can do it this way:

    wget -q -O - http://www.abc.net.au/res/streaming/audio/mp3/local_adelaide.pls

What you will see is that the stream you want to listen is actually `http://live-radio01.mediahubaustralia.com/5LRW/mp3/`. Now you can use this URL directly when you add the station to Goodvibes, and it will work.

**Comment by elboulangero** [comment]
The issue here is that the keyword used to give the number of streams is `NumberOfEvents`, while we only expect `NumberOfEntries`.

**Comment by elboulangero** [comment]
Fixed in `master`. Thanks for reporting !

**Comment by orschiro** [comment]
Wow, thanks so much for all your support and your quick fix! :-)

**Comment by elboulangero** [comment]
No worries mate :)
