### ISSUE TITLE
Offline support?

### ISSUE THREAD

**Issue by orschiro** [elboulangero/goodvibes#68]
Dear @elboulangero,

I am just wondering how difficult it is to add some kind of offline support. 

I think it would be great to have some sort of a cache to continue listening for a certain time even when offline. :-)

What do you think?

**Comment by elboulangero** [comment]
Well, the stream is fed in real-time by the server, so basically, if you want a 1 minute cache to listen after going offline, you need to be willing to wait 1 minute between the moment you press "Play", and the moment you start to hear sound. And the sound you hear is one minute late compared to what's send by the server. That's what a one minute cache is.

Not sure I explain it well. In other words: what you ask is not possible. If you want to listen stuff when offline, you need to have it recorded beforehand. It's what podcasts are for.

**Comment by orschiro** [comment]
> Not sure I explain it well. In other words: what you ask is not possible. If you want to listen stuff when offline, you need to have it recorded beforehand. It's what podcasts are for.

That makes sense. I guess I didn't think about it well enough before opening this issue. Sorry for that.

Podcasting or using a recording software are viable alternatives.
