### ISSUE TITLE
Station list parsing fails if name of the station contains "&" symbol.

### ISSUE THREAD

**Issue by stylemistake** [elboulangero/goodvibes#69]
This happened to me today, I added a station, which I called: `42FM - Steal & Kill`

After adding that station through the UI and restarting the app, built-in playlist is loaded instead.

Here's an XML entry:

```
<Stations>
  ...
  <Station>
    <uri>http://listen.42fm.ru:8000/stealkill-5.0.ogg</uri>
    <name>42FM - Steal & Kill</name>
  </Station>
  ...
</Stations>
```

I think the solution is to encode/decode XML entities.

**Comment by stylemistake** [comment]
I found the code that creates an xml of the station list: https://github.com/elboulangero/goodvibes/blob/master/src/core/gv-station-list.c#L370-L412

It seems that all strings are going through `g_markup_escape_text`, but the resulting file seems to contain unescaped strings. :thinking:

**Comment by elboulangero** [comment]
Good catch :)

Indeed, some special characters need to be escaped for the XML output. I thought that `g_markup_escape_text` was the right tool for the job, but maybe I was wrong. I'm not familiar with that stuff.

As you suggested in #71, avoiding special characters is a good workaround. I'll try to fix that soon.

**Comment by orschiro** [comment]
> As you suggested in #71, avoiding special characters is a good workaround. I'll try to fix that soon.

Thank you! For me the problem came from using the Polish character `ó`. Without that it worked well. :-)
