### ISSUE TITLE
Radio stations are reset to default

### ISSUE THREAD

**Issue by orschiro** [elboulangero/goodvibes#71]
Not sure how this happens but it already happened twice. 

I closed the UI, went on with my work, suspended my computer, resumed, and reopened Goodvibes. 

After reopening, I see that all my stations are gone and the default set of stations had been restored. 

Not sure why, not sure how.

This is what I see after reopening now:

![image](https://user-images.githubusercontent.com/170947/34420185-7aae850a-ec08-11e7-8817-b69a685a771a.png)

**Comment by stylemistake** [comment]
This is related to #69

**Comment by stylemistake** [comment]
Simple workaround: avoid `<`, `>`, `&` symbols in station name and url.

**Comment by orschiro** [comment]
Thanks! Let me try that out...

**Comment by elboulangero** [comment]
Does it fix your problem ?

**Comment by elboulangero** [comment]
Duplicate of #69
