### ISSUE TITLE
Automatically resume playback after resume from suspend

### ISSUE THREAD

**Issue by orschiro** [elboulangero/goodvibes#72]
A feature I found with [Gradio](https://github.com/haecker-felix/gradio) which I think could also greatly benefit Goodvibes. With Gradio, I can use it as follows:

1. Play radio
2. Close laptop lid
3. Laptop suspends
4. Reopen lid. 
5. Laptop resumes
6. Radio playback automatically starts again

Can we implement this with Goodvibes, too? :-)

**Comment by elboulangero** [comment]
I guess it's possible and it makes sense anyway. Just need to do some tests and understand what's going on.

**Comment by orschiro** [comment]
@elboulangero great! Please let me know if I can help testing or give any other form of feedback. :-)

**Comment by elboulangero** [comment]
No worries I will tell you when there's some news :)

**Comment by elboulangero** [comment]
Fixed through d039122.

With this change we retry playback on failure, as a consequence it will very likely resume playback when the machine resumes from suspend. But this is no bullet-proof, there are things out of our control, like pulseaudio failure. I've seen it, it's real ;)

So, as long as we receive an error from the GStreamer backend, we retry, and most likely succeed !

Try it out in the next release !

**Comment by orschiro** [comment]
Thank you so much for implementing this @elboulangero! :-)
