### ISSUE TITLE
Feature add possibility to configurable delay

### ISSUE THREAD

**Issue by jerome-laforge** [elboulangero/goodvibes#74]
Hello,
It is possible to add possibility a configurable delay.
I like to listen the live with XX second of delay in comparison of live radio.
Thx

**Comment by elboulangero** [comment]
Hi,
I don't really understand the use-case. Why exactly would you want to delay the stream ? I don't see any reason to do that.

By `XX` seconds, you mean something like 10 seconds, or more like 1000 seconds ?

**Comment by jerome-laforge** [comment]
Hello,
My usecase is:
I like watch some stuff on TV, but listen the sound on radio. 
And I try to sync the video and audio.

By `xx` seconds, this is more a configurable duration (but no more than 60 seconds).

**Comment by elboulangero** [comment]
Hey Jerome,

sorry but it looks to me like a very personal feature. Apart from you only, I don't think anyone would benefit from that. So I can't integrate that into Goodvibes.

**Comment by elboulangero** [comment]
For this kind of hack, I recommend that you get started with `gst-launch-1.0` on the command-line. On Debian, you should install the package `gstreamer1.0-tools`.

    sudo apt install gstreamer1.0-tools

Then, looking around on the Net, I found this post which suggests a solution: <https://stackoverflow.com/a/40196962/776208>.

After fiddling a bit with the command-line, I managed to get this command working:

    gst-launch-1.0 \
        souphttpsrc location='http://direct.fipradio.fr/live/fip-midfi.mp3' ! \
        decodebin ! \
        autoaudiosink ts-offset=5000000000

It's unclear how much of a delay it is, the value for `ts-offset` must be very big. You can play a bit with this value to see if it gets you somewhere.

If you're happy with that, you can then even use this value in Goodvibes. Open the *Preferences* window, enable the *Custom Output Pipeline*, and fill the text entry with something like:

    autoaudiosink ts-offset=5000000000

Then click *Apply*. Then play a station. Notice now how there is a delay between the moment the playback status becomes "Playing" and the moment you actually hear the sound. That's it, now you have a delay.

Anytime, you can go back to your Preferences to enable or disable this custom pipeline.

Happy hacking !
