### ISSUE TITLE
top bar icon and gnome

### ISSUE THREAD

**Issue by dln949** [elboulangero/goodvibes#75]
Ubuntu 17.10 (x11), gnome 3.26.2, Goodvibes 0.3.4.  

If I run Goodvibes --status-icon, should I expect to see the Goodvibes icon in the top bar?  When I run that command nothing appears in the top bar.  I am able to control Goodvibes via the media player indicator though.

**Comment by elboulangero** [comment]
Hi,

Debian Stretch here, GNOME 3.22, Goodvibes 0.3.4.

See screenshot attached, it works here. However for that to work like on the picture, I need to install the GNOME extension [TopIcon Plus](https://extensions.gnome.org/extension/1031/topicons/).

![screenshot from 2018-01-28 08-56-41](https://user-images.githubusercontent.com/1942580/35478212-a9cb6cae-0409-11e8-9b01-598245f0c0dc.png)

**Comment by dln949** [comment]
That resolved my issue, thanks.
