### ISSUE TITLE
Build for Windows using MinGW

### ISSUE THREAD

**Issue by rogersachan** [elboulangero/goodvibes#84]
I've had people tell me that it should be simple to compile gtk apps for windows using mingw, might try that for this app on my own time.

**Comment by rogersachan** [comment]
```
$ make
Making all in data
make[1]: Entering directory '/home/Roger/goodvibes/data'
msgfmt --desktop -d ../po --template com.elboulangero.Goodvibes.desktop.in -o com.elboulangero.Goodvibes.desktop
  GEN      com.elboulangero.Goodvibes.enums.xml
  GEN      com.elboulangero.Goodvibes.gschema.valid
com.elboulangero.Goodvibes.enums.xml:51:6  Error on line 51 char 6: Odd character 'm', expected a '>' character to end the empty-element tag 'C:'.  --strict was specified; exiting.
make[1]: *** [Makefile:873: com.elboulangero.Goodvibes.gschema.valid] Error 1
make[1]: Leaving directory '/home/Roger/goodvibes/data'
make: *** [Makefile:410: all-recursive] Error 1
```

I've gotten to the part where I'm able to make a Makefile, but running it gives me an error on a file that's generated. I've talked to people who use mingw that say this should work save for the generated file.

**Comment by rogersachan** [comment]
Depends on #53

**Comment by elboulangero** [comment]
Just for your information, I'm not a Windows developer, neither a Windows user, so I won't be able to provide support here. I don't think this is a trivial task.
