### ISSUE TITLE
Have proper icons

### ISSUE THREAD

**Issue by elboulangero** [elboulangero/goodvibes#9]
I need help for that !

- find someone who's interested in drawing icons
- also have a symbolic icon (see Rhythmbox)
- have different icons for playing, connection, stopped.

**Comment by milouse** [comment]
Have look around [OpenClipArt](https://openclipart.org/) it's often a good starting point for an icon. And thanks to the free (as in freedom) license, you can totally remix a picture if you want.

 --> https://openclipart.org/search/?query=radio

**Comment by elboulangero** [comment]
Thanks for pointing me that, I didn't know about it. I posted the project on https://projectgroupie.com/, it's a new collaboration website. Let's see how that goes.

**Comment by elboulangero** [comment]
For file name conventions: https://developer.gnome.org/ThemedIcons/

**Comment by elboulangero** [comment]
Duplicate of #51
